on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    strategy:
      matrix:
        go-version: [1.14.x]
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate the artifacts
        uses: skx/github-action-build@master
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "ROGManager.exe"