on:
  push:
    tags:
      - 'v*'
name: Build Release
jobs:
  test:
    name: Test before build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: test packages
        run: go test .\...
  publish:
    name: Create release-artifacts
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build Artifacts
        shell: powershell
        run: .\.github\build.ps1
      - name: Create Release # https://github.com/actions/upload-release-asset/issues/47#issuecomment-659071145
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('environment', process.versions);
            
            const fs = require('fs').promises;
            
            const { repo: { owner, repo }, sha } = context;
            console.log({ owner, repo, sha });

            const tag_name = context.payload.ref.replace(/\/refs\/tags\//, '');

            const release = await github.repos.createRelease({
              owner, repo,
              tag_name: tag_name,
              draft: false,
              prerelease: false,
              body: "Automated Release by GitHub Action CI. Please see tag annotation for changelog.",
              name: "Release " + tag_name,
              target_commitish: sha
            });

            console.log('created release', { release });
        
            for (let file of await fs.readdir('./build/')) {
              console.log('uploading', file);

              await github.repos.uploadReleaseAsset({
                owner, repo,
                release_id: release.data.id,
                name: file,
                data: await fs.readFile(`./build/${file}`)
              });            
            }