on: [push, pull_request]
name: Test and Build
jobs:
  test:
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Generate protobuf
        run: make proto_windows
      - name: Test
        run: go test ./...
      - name: Build
        run: go build .
